cofig/urls.py
from django.contrib import admin
from django.urls import path, include

from core.erp.views.categorias.views import CategoryListView, listar_categorias
from core.erp.views.productos.views import ProductListView
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('', listar_categorias, name='index'),
    path('admin/', admin.site.urls),
    path('', include('core.erp.urls'), name='index'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/erp/urls.py
from django.urls import path

from core.erp.views.categorias.views import *
from core.erp.views.detalles.views import ver_productos, view_general
# from core.erp.views.clientes.views import *
# from core.erp.views.dashboard.views import DashboardView
from core.erp.views.productos.views import *
# from core.erp.views.tests.views import TestView

app_name = 'erp'

urlpatterns = [

    #Catalogo
    path('<nombre>/', listar_productos, name='product_list'),
    path('', listar_categorias, name='category_list'),
    path('b', buscar_productos, name='buscar'),
    path('detail/<id>/', ver_productos, name='product_view'),
    path('total/general/', view_general, name='product_view_general'),


    # Categorias
    # path('categorias/list/', CategoryListView.as_view(), name='category_list'),

    # path('categorias/add/', CategoryCreateView.as_view(), name='category_create'),
    # path('categorias/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    # path('categorias/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # path('categorias/list/', search, name='category_list'),

    # path('categorias/form/', CategoryFormView.as_view(), name='category_form'),

    # Clientes
    # path('clientes/list/', ClientListView.as_view(), name='client_list'),
    # path('clientes/add/', ClientCreateView.as_view(), name='client_create'),
    # path('clientes/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    # path('clientes/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),

    # Productos
    # path('productos/list/', ProductListView.as_view(), name='product_list'),

    # path('productos/add/', ProductCreateView.as_view(), name='product_create'),
    # path('productos/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    # path('productos/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),


    # Home
    # path('dashboard/', DashboardView.as_view(), name='dashboard'),

    # Tests
    # path('test/', TestView.as_view(), name='tests'),
]

templates/hzt/body.html
{% extends 'home.html' %}
{% load static %}

{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'hzt/header.html' %}
        <!-- Sidebar -->
        {% include 'hzt/sidebar.html' %}

        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container">
                    <div class="row">
{#                        <div class="col-sm-6">#}
{#                            <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small></h1>#}
{#                        </div>#}
{#                        <div class="col-sm-6">#}
{#                            <ol class="breadcrumb float-sm-right">#}
{#                                <li class="breadcrumb-item"><a href="#">Home</a></li>#}
{#                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>#}
{#                            </ol>#}
{#                        </div>#}
                    </div>
                </div>
            </div>
            <section class="content">
                <div class="container-fluid">
                    {% block content_body %}

                    {% endblock %}
                </div>
            </section>
        </div>


        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}

            var html = '<p>';
                {% for message in messages %}
                    html+='{{ message }}<br>';
                {% endfor %}
            html += '</p>';

            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });

        {% endif %}
    </script>

    </body>
{% endblock %}

templates/hzt/header.html
{% load static %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white" >
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="{% url 'erp:category_list' %}" role="button">
            <i class="fas fa-bars" style="margin-left: 0.5rem"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Home</a>
      </li>
    </ul>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" style="margin-right: 20px" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block" style="display: none;">
          <form class="form-inline" action="{% url 'erp:buscar' %}">
            <div class="input-group input-group-sm" style="background-color: white;">
              <input class="form-control form-control-navbar" name="q" type="search" placeholder="Search" aria-label="Search"
              autocomplete="off">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

    </ul>

  </nav>

templates/hzt/sidebar.html
{% load static %}

 <aside class="main-sidebar sidebar-light-primary elevation-3">
    <a href="" class="brand-link" style="text-decoration: none">
        <img src="{% static 'img/logo.png' %}"
             alt="AdminLTE Logo"
             class="brand-image elevation-0"
             style="opacity: .8">
        <span class="brand-text font-weight-light">GoldenDragon</span>
    </a>
    <div class="sidebar">
{#        <div class="user-panel mt-3 pb-3 mb-3 d-flex">#}
{#            <div class="image">#}
{#                <img src="{{ request.user.get_image }}" class="img-circle" alt="User Image">#}
{#            </div>#}
{#            <div class="info">#}
{#                <a href="#" class="d-block" style="text-decoration: none">{{ request.user.username }}</a>#}
{#            </div>#}
{#        </div>#}
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Categorias</li>
                {% for c in categorias %}
                <li class="nav-item">
                    <a href="{% url 'erp:product_list' c.name %}" class="nav-link">
                        <i class="nav-icon fas fa-circle"></i>
                        <p>
                            {{ c.name }}
                        </p>
                    </a>
                </li>
                {% endfor %}
                <li class="nav-item">
{#                    <a href="{% url 'erp:product_list' 'general' %}" class="nav-link">#}
                    <a href="{% url 'erp:product_view_general' %}" class="nav-link">
                        <i class="nav-icon fas fa-circle"></i>
                        <p>
                            General
                        </p>
                    </a>
                </li>

            </ul>
        </nav>
    </div>
</aside>